Imports Microsoft.VisualBasic

Public Class geoHelp
    Public Shared Function StateAbbrToFullName(ByVal sAbbr As String) As String
        Dim sState As String = ""
        Select Case sAbbr.ToUpperInvariant
            Case "AL"
                sState = "Alabama"
            Case "AK"
                sState = "Alaska"
            Case "AZ"
                sState = "Arizona"
            Case "AR"
                sState = "Arkansas"
            Case "CA"
                sState = "California"
            Case "CO"
                sState = "Colorado"
            Case "CT"
                sState = "Connecticut"
            Case "DC"
                sState = "District of Columbia"
            Case "DE"
                sState = "Delaware"
            Case "FL"
                sState = "Florida"
            Case "GA"
                sState = "Georgia"
            Case "HI"
                sState = "Hawaii"
            Case "ID"
                sState = "Idaho"
            Case "IL"
                sState = "Illinois"
            Case "IN"
                sState = "Indiana"
            Case "IA"
                sState = "Iowa"
            Case "KS"
                sState = "Kansas"
            Case "KY"
                sState = "Kentucky"
            Case "LA"
                sState = "Louisiana"
            Case "ME"
                sState = "Maine"
            Case "MD"
                sState = "Maryland"
            Case "MA"
                sState = "Massachusetts"
            Case "MI"
                sState = "Michigan"
            Case "MN"
                sState = "Minnesota"
            Case "MS"
                sState = "Mississippi"
            Case "MO"
                sState = "Missouri"
            Case "MT"
                sState = "Montana"
            Case "NE"
                sState = "Nebraska"
            Case "NV"
                sState = "Nevada"
            Case "NH"
                sState = "New Hampshire"
            Case "NJ"
                sState = "New Jersey"
            Case "NM"
                sState = "New Mexico"
            Case "NY"
                sState = "New York"
            Case "NC"
                sState = "North Carolina"
            Case "ND"
                sState = "North Dakota"
            Case "OH"
                sState = "Ohio"
            Case "OK"
                sState = "Oklahoma"
            Case "OR"
                sState = "Oregon"
            Case "PA"
                sState = "Pennsylvania"
            Case "RI"
                sState = "Rhode Island"
            Case "SC"
                sState = "South Carolina"
            Case "SD"
                sState = "South Dakota"
            Case "TN"
                sState = "Tennessee"
            Case "TX"
                sState = "Texas"
            Case "UT"
                sState = "Utah"
            Case "VT"
                sState = "Vermont"
            Case "VA"
                sState = "Virginia"
            Case "WA"
                sState = "Washington"
            Case "WV"
                sState = "West Virginia"
            Case "WI"
                sState = "Wisconsin"
            Case "WY"
                sState = "Wyoming"
        End Select
        Return sState
    End Function
End Class
